### ISSUE TITLE
Created notes are empty

### ISSUE THREAD

**Issue by robert-johansson** [akopdev/obsidian-cite-manager#6]
I have been looking for this type of plugin - that also runs on mobile - for years!! Wonderful!

However, I can’t the plugin to work. After I have installed the plugin, I execute the command “BiBTeX manager: Create” (or Insert), and paste a BiBTeX entry there (like the one below). However, only an empty file “Untitled” is created.

I use latest Obsidian on iPadOS.

```
@booklet{CitekeyNewBooklet,
 title        = "Guide to the Alpine Flora",
 author       = "Elisabeth Schmitt",
 howpublished = "Available at the Bern Tourism Office",
 month        = aug,
 year         = 2018
}
```

**Comment by akopdev** [comment]
Hi @robert-johansson, could you please check and confirm:

- You have defined a template for `booklet` type (Settings -> BibTeX Manager -> Templates)
- Your template contains variables

Here is an example template that I used for testing

```markdown
# {{title}}

**Author**: {{author}}
**Publisher**: {{howpublished}}
**Year**: {{year}}
```

**Comment by robert-johansson** [comment]
@akopdev Ah - I had not defined the templates! Wonderful - everything works great now. Thanks a lot!
