### ISSUE TITLE
How to use it? Can you provide a demo workflow?

### ISSUE THREAD

**Issue by piyushdongre-dot-com** [akopdev/obsidian-cite-manager#8]
Hi.
I wanted to have a plugin that can help me create notes with citations. Can you please provide a demo workflow. How to start creating templates, bibtex entries, demo note etc.

Thanks.

**Comment by piyushdongre-dot-com** [comment]
Figured it out on my own

**Comment by homeworkace** [comment]
Interested to find out too. I'm an hour into learning about the existence of BibTeX, and there are a lack of guides about how to properly configure Obsidian or any plugin to start turning keys into links.
